# Netlify configuration for Vite + React
[build]
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html for SPA support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
